Core/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Todo API",
        default_version="v1",
        description="This is api for todo",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="mohamadimahdieh70@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("", include("accounts.urls")),
    path("Todo/", include("Todo.urls")),
    path(
        "swagger/Todo.json/",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

Todo/api/v1/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import (
    TodoListModelViewSet,
    TodoDetailGenericViewSet,
    WeatherApiView,
)


app_name = "TodoApi"

router = DefaultRouter()
router.register("Todo", TodoListModelViewSet, basename="Todo")

urlpatterns = [
    path(
        "TodoDetail/<int:pk>",
        TodoDetailGenericViewSet.as_view(),
        name="TodoDetail",
    ),
    path("Weather/", WeatherApiView.as_view(), name="Weather"),
]

urlpatterns += router.urls

Todo/urls.py
from django.urls import path, include
from . import views

app_name = "Todo"
urlpatterns = [
    path("", views.TodoList.as_view(), name="Todolist"),
    path("Create/", views.TodoCreate.as_view(), name="Create"),
    path("Edit/<int:pk>", views.EditeTodo.as_view(), name="Edit"),
    path("Delete/<int:pk>", views.DeleteTodo.as_view(), name="Delete"),
    path("api/v1/", include("Todo.api.v1.urls")),
]

accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.LoginUser.as_view(), name="login"),
    path("logout/", views.logout, name="logout"),
    path("Register/", views.RegisterUser.as_view(), name="Register"),
    path("api/v1/", include("accounts.api.v1.urls")),
    # path('api/v2/',include('djoser.urls')),
    # path('api/v2/',include('djoser.urls.jwt')),
]

Todo/models.py
from django.db import models
from accounts.models import User


class Todo(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="todouser",
    )
    Title = models.TextField()
    CreateDate = models.DateField(auto_now_add=True)
    Is_active = models.BooleanField(default=True)
    EditeDate = models.DateField(auto_now=True)
    Completed = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.Title}-{self.user}-{self.CreateDate}"

Todo/api/v1/views.py
from .serializer import TodoSerializer, CitySerializer
from ...models import Todo
from rest_framework import viewsets, generics
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.filters import OrderingFilter, SearchFilter
from django_filters.rest_framework import DjangoFilterBackend
from .pagination import TodolistPage
from rest_framework import status
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie


class TodoListModelViewSet(viewsets.ModelViewSet):
    """
    this is ModelViewSet for View and Create Todo
    """

    queryset = Todo.objects.all()
    serializer_class = TodoSerializer
    permission_classes = [IsAuthenticated]
    filter_backends = [OrderingFilter, SearchFilter, DjangoFilterBackend]
    filterset_fields = {"Title": ["in"]}
    search_fields = ["Title"]
    ordering_fields = ["CreateDate"]
    pagination_class = TodolistPage

    def list(self, request, *args, **kwargs):
        """
        this is ModelViewSet for View Todo
        """
        queryset = self.filter_queryset(
            self.get_queryset().filter(user=self.request.user)
        )
        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)
        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)

    def perform_create(self, serializer):
        """
        this is ModelViewSet for Save Create Todo
        """
        serializer.save(user=self.request.user)


class TodoDetailGenericViewSet(generics.RetrieveUpdateDestroyAPIView):
    """
    this is for TodoDetail
    """

    queryset = Todo.objects.all()
    serializer_class = TodoSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        queryset = self.queryset.filter(user=self.request.user)
        return queryset


class WeatherApiView(generics.GenericAPIView):
    serializer_class = CitySerializer

    @method_decorator(cache_page(60 * 20))
    @method_decorator(vary_on_cookie)
    def post(self, request):
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            city = serializer.data.get("cityname")
            city_weather = serializer.validated_data["city_weather"]
            weather = {
                "city": city,
                "temperature": str(city_weather["main"]["temp"]),
                "description": str(city_weather["weather"][0]["description"]),
                "icon": str(city_weather["weather"][0]["icon"]),
                "temperature_max": str(city_weather["main"]["temp_max"]),
                "temperature_min": str(city_weather["main"]["temp_min"]),
                "feelslike_weather": str(city_weather["main"]["feels_like"]),
            }
            return Response(weather, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

Todo/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from .models import Todo


user = get_user_model()


class TodoCreate(CreateView):
    model = Todo
    template_name = "Todo/index.html"
    fields = ("Title",)
    success_url = reverse_lazy("Todo:Todolist")

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()
        return super(TodoCreate, self).form_valid(form)


class EditeTodo(UpdateView):
    template_name = "Todo/Update.html"
    model = Todo
    fields = ("Title", "Completed")
    success_url = reverse_lazy("Todo:Todolist")


class DeleteTodo(DeleteView):
    template_name = "Todo/Delete.html"
    model = Todo
    success_url = reverse_lazy("Todo:Todolist")


class TodoList(ListView):
    model = Todo
    template_name = "Todo/index.html"

    def get_queryset(self):
        request = self.request
        userget = self.request.user
        active = request.GET.get("active")
        completed = request.GET.get("completed")
        alluser = request.GET.get("all")

        if active:
            queryset = userget.todouser.filter(Is_active=True)
            return queryset
        elif completed:
            queryset = userget.todouser.filter(Completed=True)
            return queryset
        elif alluser:
            queryset = userget.todouser.all()
            return queryset
        else:
            queryset = userget.todouser.all()
            return queryset

    def get_context_data(self, **kwargs):
        context = super(TodoList, self).get_context_data()
        return context

Todo/templates/Todo/Delete.html
{% extends '_base.html' %}
{% load static %}


{% block title %}
 Todo App
{% endblock %}

{% block content %}

    <div class="container m-5 p-2 rounded mx-auto bg-light shadow">
    <div class="text-lg-right">
        <button><a href="{% url 'accounts:login' %}">Logout /</a></button>
        <button><a href="#">{{request.user}}</a></button>
    </div>
    <!-- App title section -->
    <div class="row m-1 p-4">
        <div class="col">
            <div class="p-1 h1 text-primary text-center mx-auto display-inline-block">
                <i class="fa fa-check bg-primary text-white rounded p-2"></i>
                <u>My Todo-s</u>
            </div>
        </div>
    </div>
    <!-- Create todo section -->
    <div class="row m-1 p-3">
        <div class="col col-11 mx-auto">
           <form method="post">{% csrf_token %}
            <div class="">

                    <div class="col">
                    </div>
                     <div class="col  text-center " style="margin-right: 50%">
                         <h5 class="m-3">Dearuser <span style="color:#7653ff">{{ request.user }}</span>Are you sure you want to delete?</h5>
                        <div>
                          <button type="submit" class="btn btn-primary m-3 alert-success">Yes</button>
                          <a href="{% url 'Todo:Todolist' %}"><button type="button" class="btn btn-primary alert-danger">No</button></a>
                        </div>
                     </div>

            </div>
           </form>
        </div>
    </div>
    <div class="p-2 mx-4 border-black-25 border-bottom"></div>


</div>
{% endblock %}

Todo/templates/Todo/Update.html
{% extends '_base.html' %}
{% load static %}


{% block title %}
 Todo App
{% endblock %}

{% block content %}

    <div class="container m-5 p-2 rounded mx-auto bg-light shadow">
    <div class="text-lg-right">
        <button><a href="{% url 'accounts:login' %}">Logout /</a></button>
        <button><a href="#">{{request.user}}</a></button>
    </div>
    <!-- App title section -->
    <div class="row m-1 p-4">
        <div class="col">
            <div class="p-1 h1 text-primary text-center mx-auto display-inline-block">
                <i class="fa fa-check bg-primary text-white rounded p-2"></i>
                <u>My Todo-s</u>
            </div>
        </div>
    </div>
    <!-- Create todo section -->
    <div class="row m-1 p-3">
        <div class="col col-11 mx-auto">
           <form method="post">{% csrf_token %}
            <div class="row bg-white rounded shadow-sm p-2 add-todo-wrapper align-items-center justify-content-center">

                    <div class="col">

                       <input type="text" class="form-control form-control-lg " name="Title" value="{{ form.Title.value }}">
                    </div>
                    <div class="form-check p-4">
                           <input type="checkbox" class="form-check-input" name="Completed" {% if form.Completed.value %} checked  {% endif %}value="{{ form.Title.value }}">
                    </div>
                     <div class="col-auto px-0 mx-0 mr-2">
                          <button type="submit" class="btn btn-primary">Save</button>
                     </div>

            </div>
           </form>
        </div>
    </div>
    <div class="p-2 mx-4 border-black-25 border-bottom"></div>


</div>
{% endblock %}

Todo/templates/Todo/index.html
{% extends '_base.html' %}
{% load static %}


{% block title %}
 Todo App
{% endblock %}

{% block content %}

    <div class="container m-5 p-2 rounded mx-auto bg-light shadow">
    <div class="text-lg-right">
        <button><a href="{% url 'accounts:login' %}">Logout /</a></button>
        <button><a href="#">{{request.user}}</a></button>
    </div>
    <!-- App title section -->
    <div class="row m-1 p-4">
        <div class="col">
            <div class="p-1 h1 text-primary text-center mx-auto display-inline-block">
                <i class="fa fa-check bg-primary text-white rounded p-2"></i>
                <u>My Todo-s</u>
            </div>
        </div>
    </div>
    <!-- Create todo section -->
    <div class="row m-1 p-3">
        <div class="col col-11 mx-auto">
           <form method="post" action="{% url 'Todo:Create' %}">{% csrf_token %}
            <div class="row bg-white rounded shadow-sm p-2 add-todo-wrapper align-items-center justify-content-center">

                    <div class="col">
                        <input class="form-control form-control-lg border-0 add-todo-input bg-transparent rounded" type="text" name="Title" placeholder="Add new ..">
                    </div>
                    <div class="col-auto m-0 px-2 d-flex align-items-center">
                        <label class="text-secondary my-2 p-0 px-1 view-opt-label due-date-label d-none">Due date not set</label>
                        <i class="fa fa-calendar my-2 px-1 text-primary btn due-date-button" data-toggle="tooltip" data-placement="bottom" title="Set a Due date"></i>
                        <i class="fa fa-calendar-times-o my-2 px-1 text-danger btn clear-due-date-button d-none" data-toggle="tooltip" data-placement="bottom" title="Clear Due date"></i>
                     </div>
                     <div class="col-auto px-0 mx-0 mr-2">
                          <button type="submit" class="btn btn-primary">Add</button>
                     </div>

            </div>
           </form>
        </div>
    </div>
    <div class="p-2 mx-4 border-black-25 border-bottom"></div>
    <!-- View options section -->
    <div class="row m-1 p-3 px-5 justify-content-end">
        <div class="col-auto d-flex align-items-center">
            <label class="text-secondary my-2 pr-2 view-opt-label">Filter</label>
            <select class="custom-select custom-select-sm btn my-2"  onchange="location=this.value;">
                <option value="{% url 'Todo:Todolist' %}?all=1" {% if request.get_full_path == '/Todo/?all=1'%}selected{% endif %}>All</option>
                <option value="{% url 'Todo:Todolist' %}?completed=1" {% if request.get_full_path == '/Todo/?completed=1'%}selected{% endif %}>Completed</option>
                <option value="{% url 'Todo:Todolist' %}?active=1" {% if request.get_full_path == '/Todo/?active=1'%}selected{% endif %}>Active</option>
            </select>
        </div>
        <div class="col-auto d-flex align-items-center px-1 pr-3">
            <label class="text-secondary my-2 pr-2 view-opt-label">Sort</label>
            <select class="custom-select custom-select-sm btn my-2" onchange="location = this.value;">
                <option value="{% url 'Todo:Todolist' %}?date=Added-date" selected>Added date</option>
                <option value="{% url 'Todo:Todolist' %}?date=Edite-date">Edite date</option>
            </select>
            <i class="fa fa fa-sort-amount-asc text-info btn mx-0 px-0 pl-1" data-toggle="tooltip" data-placement="bottom" title="Ascending"></i>
            <i class="fa fa fa-sort-amount-desc text-info btn mx-0 px-0 pl-1 d-none" data-toggle="tooltip" data-placement="bottom" title="Descending"></i>
        </div>
    </div>
    <!-- Todo list section -->
    <div class="row mx-1 px-5 pb-3 w-80">
        <div class="col mx-auto">
            <!-- Todo Item 1 -->
            {% for todoobject in object_list %}

                 <div class="row px-3 align-items-center todo-item rounded">
                    <div class="col-auto m-1 p-0 d-flex align-items-center">
                        <h2 class="m-0 p-0">

                            {% if todoobject.Completed %}
                                 <i class="fa fa-check-square-o text-primary btn m-0 p-0 " data-toggle="tooltip" data-placement="left" title="Mark as complete"></i>
                            {% else %}
                                 <i class="fa fa-square-o text-primary btn m-0 p-0 " data-toggle="tooltip" data-placement="left" title="Mark as Todo" ></i>
                            {% endif %}
                        </h2>
                    </div>
                    <div class="col px-1 m-1 d-flex align-items-center">
                        <input type="text" class="form-control form-control-lg border-0 edit-todo-input bg-transparent rounded px-3" readonly value="{{ todoobject.Title }}" title="{{ todoobject.Title }}" />
                        <input type="text" class="form-control form-control-lg border-0 edit-todo-input rounded px-3 d-none" value="{{ todoobject.Title }}" />
                    </div>
                    <div class="col-auto m-1 p-0 px-3 d-none">
                    </div>
                    <div class="col-auto m-1 p-0 todo-actions">
                            <div class="row d-flex align-items-center justify-content-end">
                                <h5 class="m-0 p-0 px-2">
                                    <a href="{% url 'Todo:Edit' todoobject.id %}"><i class="fa fa-pencil text-info btn m-0 p-0" data-toggle="tooltip" data-placement="bottom" title="Edit todo"></i></a>
                                </h5>
                                <h5 class="m-0 p-0 px-2">
                                    <a href="{% url 'Todo:Delete' todoobject.id %}"><i class="fa fa-trash-o text-danger btn m-0 p-0" data-toggle="tooltip" data-placement="bottom" title="Delete todo"></i></a>
                                </h5>
                            </div>
                            <div class="row todo-created-info">
                                <div class="col-auto d-flex align-items-center pr-2">
                                    <i class="fa fa-info-circle my-2 px-2 text-black-50 btn" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Created date"></i>
                                    <label class="date-label my-2 text-black-50">{{ todoobject.CreateDate }}</label>
                                </div>
                            </div>
                    </div>
                </div>
            {% endfor %}


        </div>
    </div>
</div>
 <script>
    $(document).ready(function(){
      $('[data-toggle="tooltip"]').tooltip();
    });
</script>
{% endblock %}